'use strict';
// Shared UI text for page scripts. Korean is the source text; English is written next to it
// in each call, and French, Spanish, Chinese and Japanese come from i18n-data.js
// (generated by tools/build_i18n.py). JSB_T(ko, en, vars) returns the text for <html lang>,
// falls back to English, and fills {placeholders} from vars.
(function () {
  var lang = (document.documentElement.lang || 'ko').slice(0, 2).toLowerCase();
  var data = (window.JSB_I18N_DATA || {})[lang] || {};
  window.JSB_LANG = lang;
  window.JSB_T = function (ko, en, vars) {
    var text = lang === 'ko' ? ko : (lang === 'en' ? en : (data[ko] || en));
    if (vars) Object.keys(vars).forEach(function (key) { text = text.split('{' + key + '}').join(String(vars[key])); });
    return text;
  };
})();
