const T=(ko,en,vars)=>window.JSB_T?window.JSB_T(ko,en,vars):en;
(()=>{'use strict';
 const reduced=matchMedia('(prefers-reduced-motion: reduce)');let paused=reduced.matches;try{paused=paused||sessionStorage.getItem('jsb-motion')==='paused'}catch{}
 const toggle=document.createElement('button');toggle.type='button';toggle.className='motion-toggle';(document.querySelector('footer')||document.body).append(toggle);
 function apply(){document.body.classList.toggle('motion-paused',paused);toggle.textContent=paused?T('▷ 움직임 켜기','▷ Resume motion'):T('Ⅱ 움직임 멈추기','Ⅱ Pause motion');toggle.setAttribute('aria-pressed',String(paused));document.dispatchEvent(new CustomEvent('motionchange',{detail:{paused}}));}toggle.addEventListener('click',()=>{paused=!paused;try{sessionStorage.setItem('jsb-motion',paused?'paused':'running')}catch{}apply()});reduced.addEventListener('change',()=>{paused=reduced.matches;apply()});apply();
 document.querySelectorAll('.marquee-track,.focus-strip,.ribbon,.airport-marquee-track').forEach(track=>{const children=[...track.children];if(!children.length)return;let count=children.length;if(track.classList.contains('marquee-track'))count/=2;if(track.classList.contains('ribbon')){const shell=document.createElement('div');shell.className='motion-shell';track.before(shell);shell.append(track)}const group=document.createElement('div');group.className='motion-loop';children.slice(0,count).forEach(c=>group.append(c.cloneNode(true)));track.replaceChildren(group);const copy=group.cloneNode(true);copy.setAttribute('aria-hidden','true');track.append(copy);track.classList.add('motion-track');});
 // A slim route at the outer edge tracks reading progress without covering content.
 const flight=document.createElement('div');flight.className='flight-progress';flight.setAttribute('aria-hidden','true');
 flight.innerHTML='<span class="flight-end flight-start"></span><span class="flight-path"><i class="flight-fill"></i></span><span class="flight-plane"><svg viewBox="0 0 24 24" fill="currentColor"><path d="M11 2h2l1 7 8 5v2l-8-2-1 6 3 2v1l-4-1-4 1v-1l3-2-1-6-8 2v-2l8-5z"/></svg></span><span class="flight-end flight-arrival"></span><span class="flight-percent">00</span>';
 document.body.append(flight);let scheduled=false;
 function update(){const height=document.documentElement.scrollHeight-innerHeight;const ratio=Math.max(0,Math.min(1,height>0?scrollY/height:0));flight.style.setProperty('--flight-ratio',ratio);flight.querySelector('.flight-percent').textContent=String(Math.round(ratio*100)).padStart(2,'0');flight.classList.toggle('arrived',ratio>=.995);scheduled=false;}
 const queue=()=>{if(!scheduled){requestAnimationFrame(update);scheduled=true}};
 addEventListener('scroll',queue,{passive:true});addEventListener('resize',queue);addEventListener('load',queue);new ResizeObserver(queue).observe(document.body);update();
 const hero=document.querySelector('.hero-card');if(hero&&matchMedia('(hover:hover) and (pointer:fine)').matches){hero.classList.add('motion-tilt');hero.addEventListener('pointermove',e=>{if(paused)return;const r=hero.getBoundingClientRect();hero.style.setProperty('--ry',`${((e.clientX-r.left)/r.width-.5)*6}deg`);hero.style.setProperty('--rx',`${((e.clientY-r.top)/r.height-.5)*-5}deg`)});const reset=()=>{hero.style.setProperty('--rx','0deg');hero.style.setProperty('--ry','0deg')};hero.addEventListener('pointerleave',reset);document.addEventListener('motionchange',reset)}
 const rail=document.querySelector('.moment-rail');if(!rail)return;const cards=[...rail.children],opens=[...rail.querySelectorAll('.moment-open')],dialog=document.querySelector('.photo-dialog');let selected=0,trigger,previousOverflow='';
 let autoPlaying=true,railVisible=false;const autoButton=document.querySelector('.moment-autoplay');
 function autoLabel(){if(autoButton){autoButton.textContent=autoPlaying?T('자동 넘김 멈추기 Ⅱ','Pause slideshow Ⅱ'):T('자동 넘김 켜기 ▷','Resume slideshow ▷');autoButton.setAttribute('aria-pressed',String(autoPlaying));}}
 autoButton?.addEventListener('click',()=>{autoPlaying=!autoPlaying;autoLabel()});
 const stopAuto=()=>{autoPlaying=false;autoLabel()};rail.addEventListener('pointerdown',stopAuto);rail.addEventListener('keydown',stopAuto);document.querySelectorAll('[data-slide]').forEach(b=>b.addEventListener('click',stopAuto));
 new IntersectionObserver(entries=>{railVisible=entries[0].isIntersecting},{threshold:.2}).observe(rail);
 setInterval(()=>{if(!autoPlaying||!railVisible||paused||document.hidden||dialog.open||rail.matches(':hover,:focus-within'))return;const max=rail.scrollWidth-rail.clientWidth;rail.scrollTo({left:rail.scrollLeft>=max-5?0:Math.min(max,rail.scrollLeft+measure()),behavior:'smooth'});},6500);
 const measure=()=>cards[1]?cards[1].offsetLeft-cards[0].offsetLeft:rail.clientWidth;function status(){const fraction=rail.scrollLeft/Math.max(1,rail.scrollWidth-rail.clientWidth);document.querySelector('.moment-count').textContent=`${String(Math.min(cards.length,Math.round(fraction*(cards.length-1))+1)).padStart(2,'0')} / 05`;document.querySelector('.moment-progress i').style.transform=`translateX(${fraction*400}%)`;}rail.addEventListener('scroll',status,{passive:true});addEventListener('resize',status);document.querySelectorAll('[data-slide]').forEach(b=>b.addEventListener('click',()=>rail.scrollBy({left:measure()*Number(b.dataset.slide),behavior:paused?'instant':'smooth'})));rail.addEventListener('keydown',e=>{if(e.target===rail&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();rail.scrollBy({left:measure()*(e.key==='ArrowRight'?1:-1),behavior:paused?'instant':'smooth'})}});
 let drag=null,dragged=false;rail.addEventListener('pointerdown',e=>{if(e.pointerType!=='mouse'||e.button!==0)return;drag={x:e.clientX,left:rail.scrollLeft};dragged=false});rail.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x;if(Math.abs(dx)>7){dragged=true;rail.classList.add('dragging');e.preventDefault();rail.scrollLeft=drag.left-dx}});const end=()=>{drag=null;rail.classList.remove('dragging')};addEventListener('pointerup',end);rail.addEventListener('pointerleave',end);rail.addEventListener('dragstart',e=>e.preventDefault());rail.addEventListener('click',e=>{if(dragged){e.preventDefault();e.stopPropagation();dragged=false}},true);
 function render(){const card=cards[selected],img=card.querySelector('img'),large=dialog.querySelector('.photo-large');large.src=img.src;large.alt=img.alt;dialog.querySelector('#photo-title').textContent=card.querySelector('h3').textContent;dialog.querySelector('#photo-description').textContent=card.querySelector('.moment-copy p').textContent;dialog.querySelector('#photo-source').textContent=card.querySelector('.moment-source').textContent;dialog.querySelector('#photo-number').textContent=`${String(selected+1).padStart(2,'0')} / 05 — JSB COMPANY ARCHIVE`}
 opens.forEach((button,i)=>button.addEventListener('click',()=>{selected=i;trigger=button;render();previousOverflow=document.body.style.overflow;document.body.style.overflow='hidden';dialog.showModal();dialog.querySelector('.photo-close').focus()}));dialog.querySelector('.photo-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{document.body.style.overflow=previousOverflow;trigger?.focus()});function step(n){selected=(selected+n+cards.length)%cards.length;render()}dialog.querySelectorAll('[data-photo-step]').forEach(b=>b.addEventListener('click',()=>step(Number(b.dataset.photoStep))));dialog.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();step(e.key==='ArrowRight'?1:-1)}});status();
})();
